### ISSUE TITLE
User Story: Selecting Parameters

### ISSUE THREAD

**Issue by cjphawes** [cjphawes/travel-website-project-4#2]
As a **user**, I can **change the date and time of my preferred flight times** so that **I can see available flights within my parameters**.

### Acceptance Criteria
- Selecting particular dates for one-way & round trips.
- Selecting times in conjunction with the date.
- Choosing the amount of people involved in the search.

### Tasks
- [ ] Create a search box outline, with 4 different extra boxes and a button inside.
- [ ] Create a destination search box. 
- [ ] Create a selectable date and time table.
- [ ] Create a selectable box to decide if the user wants to search for a one-way or round trip flight.
- [ ] Create an option to change the amount of people the search includes.
- [ ] Create a search button.
