### ISSUE TITLE
User Story: Navigating The Home Page

### ISSUE THREAD

**Issue by cjphawes** [cjphawes/travel-website-project-4#3]
As a **user**, the website provides **navigation through all of the pages via the navigation bar and footer** so that **I am able to find all the relevant information I require**.

### Acceptance Criteria
- All of the required links are made available in the navigation bar/footer.
- The pages are grouped together effectively for minimal navigation.
- They are presented in a clear, precise and visible manner for the user to easily find what they are looking for.
- Make the user be able to identify which page they are currently on for better UI experience.

### Tasks
- [ ] Create a basic navigation bar and footer.
- [ ] Add a list of links required for all the required pages.
- [ ] Develop the links into a clear and minimalistic manner.
- [ ] Create a style that allows the user to easily identify what page of the website they are currently on.
