### ISSUE TITLE
User Story: Language Availability

### ISSUE THREAD

**Issue by cjphawes** [cjphawes/travel-website-project-4#4]
As a **user**, the website allows me to **change the preferred language** so that **I am able to understand the information displayed on the webpage in my own language**.

### Acceptance Criteria
- Allow multiple language options to chose from.
- Have a button to be able to select preferred languages from.

### Tasks
- [ ] Choose languages to be selectable by the user.
- [ ] Create a drop down menu button that allows the user to change the language from the currently selected one.
- [ ] Develop the button to be identifiable by the languages flag.
