### ISSUE TITLE
User Story: Membership

### ISSUE THREAD

**Issue by cjphawes** [cjphawes/travel-website-project-4#5]
As a **user**, I am able to **sign-up to become a member** so that **I can receive exclusive discounts and alerts about cheap flights becoming available**.

### Acceptance Criteria
- Create a sign-up form allowing users to create an account.
- Create a confirmation page, giving the user positive feedback from submitting the sign-up request.
- Upon account creation, a member icon shall be displayed to show their log in status.

### Tasks
- [ ] Create a sign-up button in the navigation bar.
- [ ] Create a sign-up form template.
- [ ] Create input information for personal details such as Names; first and last, email address, password, .
- [ ] \(Alternative) Create Google and Facebook account authorisations for log ins.
- [ ] Create a confirmation webpage positively identifying their account creation was successful.
- [ ] Create a selectable drop down menu button in the navigation bar that displays a member icon.
