### ISSUE TITLE
User Story: FAQ's

### ISSUE THREAD

**Issue by cjphawes** [cjphawes/travel-website-project-4#6]
As a **user**, the website offers **a FAQ's section** so that **questions/queries/doubts I have, they can be answered by looking through that section**.

### Acceptance Criteria
- A list of 4-5 commonly asked questions with appropriate answers.
- A section separate from other parts of the webpage making it easily identifiable to the user

### Tasks
- [ ] Create a section for the FQA's to be placed into.
- [ ] Come up with 4-5 common questions asked and answer them appropriately.
- [ ] Style the individual boxes in a minimalistic way, so that the user can easily select and view the answers without any ambiguity.
