### ISSUE TITLE
User Story: <TEMPLATE>

### ISSUE THREAD

**Issue by cjphawes** [cjphawes/travel-website-project-4#7]
As a **user**, the website allows me to **change my parameters in greater detail** so that **I am able to find the most suitable flights dependent on my needs**.

### Acceptance Criteria
- Have 4/5 options to more precisely narrow down searches.
- Have a sidebar where the options will reside.

### Tasks
- [ ] Create a sidebar where these options will situate.
- [ ] Create 4/5 options to be able to select from
- [ ] Inside the options individually, create check box selections available to the user. to click.
